export const LOAD_QUESTIONS_SUCCESS = "LOAD_QUESTIONS_SUCCESS";
export const LOAD_QUESTIONS_FAILURE = "LOAD_QUESTIONS_FAILURE";

export const ADD_ANSWER = "ADD_ANSWER";
export const CHECK_ANSWER_FAILURE = "CHECK_ANSWER_FAILURE";
export const CHECK_ANSWER_SUCCESS = "CHECK_ANSWER_SUCCESS";

// Error server constant
export const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"